[build]
  command = "NEXT_PUBLIC_API_URL=/.netlify/functions/backend npm run build:admin"
  publish = "fronti-admin/.next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/backend/*"
  to = "/.netlify/functions/backend/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/backend/api/:splat"
  status = 200
